import {
  FolderIcon,
  RectangleStackIcon,
  ServerStackIcon,
  Cog8ToothIcon,
  ChatBubbleBottomCenterIcon,
  CubeTransparentIcon,
  QueueListIcon,
  ArchiveBoxIcon,
} from '@heroicons/react/24/outline'
import { LicenseType } from '@prisma/client'

import { LuLayoutDashboard } from 'react-icons/lu'

export const workspaceMenu = (currentWorkspace?: string) => [
  {
    name: 'Workspace',
    menuItems: [
      {
        name: 'Chat+',
        href: `/workspace/${currentWorkspace}/chat`,
        description: 'Main Page',
        enabled: currentWorkspace !== undefined,
        visible: true,
        Icon: ChatBubbleBottomCenterIcon,
        license: LicenseType.TRIAL,
      },
      {
        name: 'Document Search',
        href: `/workspace/${currentWorkspace}/search`,
        description: 'Search through your documents',
        enabled: currentWorkspace !== undefined,
        visible: true,
        Icon: RectangleStackIcon,
        license: LicenseType.TRIAL,
      },

      // {
      //   name: 'Data Analysis',
      //   href: `/workspace/${currentWorkspace}/data`,
      //   description: 'Analyze your documents',
      //   enabled: currentWorkspace !== '',
      //   visible: true,
      //   Icon: ChatBubbleBottomCenterIcon,
      // },
      {
        name: 'Workflows',
        href: `/workspace/${currentWorkspace}/flow`,
        description: 'Custom Workflows, Agents and Models',
        enabled: currentWorkspace !== undefined,
        visible: true,
        Icon: CubeTransparentIcon,
        license: LicenseType.OPEN,
      },

      {
        name: 'Threads',
        href: `/workspace/${currentWorkspace}/threads`,
        description: 'Organize your works',
        enabled: currentWorkspace !== undefined,
        visible: true,
        Icon: QueueListIcon,
        license: LicenseType.TRIAL,
      },
      // {
      //   name: 'Integrations',
      //   href: '/integrations',
      //   description: 'Integrated Services',
      //   enabled: false,
      //   visible: true,
      //   Icon: PuzzlePieceIcon,
      // },
      {
        name: 'File Management',
        href: `/workspace/${currentWorkspace}/files`,
        description: 'File Management',
        enabled: currentWorkspace !== undefined,
        visible: true,
        Icon: ServerStackIcon,
        license: LicenseType.TRIAL,
      },
      {
        name: 'Workspace Settings',
        href: `/workspace/${currentWorkspace}/settings`,
        description: 'Status and Monitoring',
        enabled: currentWorkspace !== undefined,
        visible: true,
        Icon: Cog8ToothIcon,
        license: LicenseType.TRIAL,
      },
    ],
  },
  {
    name: 'organization',
    menuItems: [
      {
        name: 'Workflow Editor',
        href: '/editor',
        description: 'No-code workflow editor',
        enabled: true,
        visible: true,
        Icon: LuLayoutDashboard,
        license: LicenseType.OPEN,
      },
      {
        name: 'Manage Workspaces',
        href: '/workspaces',
        description: 'Main Page',
        enabled: true,
        visible: true,
        Icon: RectangleStackIcon,
        license: LicenseType.TRIAL,
      },
      {
        name: 'Manage Models',
        href: '/models',
        description: 'Manage your LLM Models',
        enabled: true,
        visible: true,
        Icon: RectangleStackIcon,
        license: LicenseType.TRIAL,
      },
      {
        name: 'Manage Prompts',
        href: '/prompts',
        description: 'Manage your LLM Prompts',
        enabled: true,
        visible: true,
        Icon: RectangleStackIcon,
        license: LicenseType.TRIAL,
      },

      {
        name: 'Training (coming soon)',
        href: '/training',
        description: 'Learning to use the system',
        enabled: false,
        visible: true,
        Icon: FolderIcon,
        license: LicenseType.OPEN,
      },
      {
        name: 'Team Management',
        href: `/organization`,
        description: 'Handle team members',
        enabled: true,
        visible: true,
        Icon: ArchiveBoxIcon,
        license: LicenseType.TRIAL,
      },
      {
        name: 'Support',
        href: `/settings`,
        description: 'Settings for your organization',
        enabled: true,
        visible: true,
        Icon: ServerStackIcon,
        license: LicenseType.TRIAL,
      },
    ],
  },
]
