service: discontinuity-rag
frameworkVersion: "3"

# Uncomment this line to read the env variables from a .env local file. This is used for deploying just this
# component to a test account
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  timeout: 300

  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    S3_AWS_SECRET_KEY: ${env:S3_AWS_SECRET_KEY}
    S3_AWS_ACCESS_KEY: ${env:S3_AWS_ACCESS_KEY}
    S3_AWS_BUCKET: ${env:S3_AWS_BUCKET}
    UNSTRUCTURED_URL: ${env:UNSTRUCTURED_URL}
    UNSTRUCTURED_API_KEY: ${env:UNSTRUCTURED_API_KEY}
    DATABASE_URL: ${env:DATABASE_URL}
    QDRANT_API_KEY: ${env:QDRANT_API_KEY}
    QDRANT_URL: ${env:QDRANT_URL}
    DB_CONNECTION: ${env:DB_CONNECTION}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::${env:S3_AWS_BUCKET}"

package:
  include:
    - google-services.json
  exclude:
    - node_modules/**
    - coverage/**
    - .idea
    - .gitignore
    - src/**
    - test/**
    - dist/**.map
    - tsconfig.json
    - package.json
    - package-lock.json

plugins:
  - serverless-esbuild

functions:
  embedding:
    handler: dist/embedding.handler
    events:
      - s3:
          bucket: ${env:S3_AWS_BUCKET}
          event: s3:ObjectCreated:*
  deletion:
    handler: dist/deletion.handler
    events:
      - s3:
          bucket: ${env:S3_AWS_BUCKET}
          event: s3:ObjectRemoved:*
