name: website-docker-build
on:
  push:
    paths:
      - "website/**"
    branches:
      - main
defaults:
  run:
    working-directory: ./website
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Setup gcloud CLI

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/discontinuity-website:${{ github.sha }}

      - uses: google-github-actions/get-gke-credentials@v1.0.2
        with:
          cluster_name: discontinuity-cluster
          location: europe-west1
          project_id: ${{ secrets.GCP_PROJECT }}

        # Deploy the Docker image to the GKE cluster
      - name: Configure kubectl
        run: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials discontinuity-cluster  --location europe-west1 --project ${{ secrets.GCP_PROJECT }}

      - name: Deploy
        run: |
          kubectl set image deployment/discontinuity-website-deployment -n=api website=gcr.io/${{ secrets.GCP_PROJECT }}/discontinuity-website:${{ github.sha }} 
          kubectl rollout status deployment/discontinuity-website-deployment -n=api
